project_id = "umhqbgsvfjatcaiwtqnr"

[functions.create-checkout]
verify_jwt = false

[functions.get-stripe-price]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.deploy-demo-site]
verify_jwt = false
